# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "sql-synthesizer-team"
    assignees:
      - "sql-synthesizer-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for critical dependencies
    ignore:
      - dependency-name: "SQLAlchemy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Flask"
        update-types: ["version-update:semver-major"]
      - dependency-name: "openai"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    reviewers:
      - "sql-synthesizer-team"
    assignees:
      - "sql-synthesizer-team"
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "dependencies"
      - "automated"

  # GitHub Actions dependencies (when workflows are added)
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "UTC"
    reviewers:
      - "sql-synthesizer-team"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"