
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-synthesizer
  labels:
    app: sql-synthesizer
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sql-synthesizer
  template:
    metadata:
      labels:
        app: sql-synthesizer
    spec:
      containers:
      - name: sql-synthesizer
        image: sql-synthesizer:latest
        ports:
        - containerPort: 5000
        env:
        - name: QUERY_AGENT_WEBAPP_PORT
          value: "5000"
        - name: QUERY_AGENT_CACHE_BACKEND
          value: "redis"
        - name: QUERY_AGENT_REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sql-synthesizer-service
spec:
  selector:
    app: sql-synthesizer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sql-synthesizer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sql-synthesizer
  minReplicas: 3
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
